# Generated by Django 5.1.2 on 2024-10-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('contrasena', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('NB', 'No Binario'), ('T', 'Transgénero'), ('O', 'Otro'), ('N', 'Prefiero no decirlo')], max_length=2)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=50)),
                ('ocupacion', models.CharField(choices=[('E', 'Estudiante'), ('I', 'Ingeniero'), ('O', 'Otro')], max_length=1)),
                ('create', models.DateField(auto_now_add=True)),
                ('update', models.DateField(auto_now_add=True)),
                ('fotoperfil', models.ImageField(upload_to='usuarios')),
            ],
        ),
    ]
