# Generated by Django 5.1.2 on 2024-10-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaMonitoreoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='direccion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fotoperfil',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('NB', 'No Binario'), ('T', 'Transgénero'), ('O', 'Otro'), ('N', 'Prefiero no decirlo')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='ocupacion',
            field=models.CharField(blank=True, choices=[('E', 'Estudiante'), ('I', 'Ingeniero'), ('O', 'Otro')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
